FROM eclipse-temurin:21.0.7_6-jdk-ubi9-minimal

EXPOSE 6379
EXPOSE 8080

COPY ./target/sse-demo-1.0.0.jar /app.jar

CMD ["java", "-jar", "-Dspring.profiles.active=docker", "-Djdk.tls.client.protocols=TLSv1.2", "/app.jar"]